# MySQL DataSource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/financemaster_db
spring.datasource.username=hlony
spring.datasource.password=Lehlohonolo@21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect