# MySQL DataSource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/FinanceMaster
spring.datasource.username=root
spring.datasource.password=Lehlohonolo@21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update